name: artifacts

on: push

env:
  artifacts_name: myartifacts

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: check out
        uses: actions/checkout@v2
      - name: upload artifacts
        uses: actions/upload-artifact@v2
        with: 
          name: ${{env.artifacts_name}}
          path: .